### ISSUE TITLE
VS Code plugin for EO

### ISSUE THREAD

**Issue by yegor256** [objectionary/ideas#11]
We already have a plugin for IntelliJ IDEA: https://github.com/objectionary/eo-intellij-plugin

Let's create one for VS Code.

**Comment by EduardoFernandes1410** [comment]
My team is going to develop it!

**Comment by yegor256** [comment]
it's done: https://github.com/objectionary/eo-vscode (big thanks to the team of @EduardoFernandes1410!)

**Comment by EduardoFernandes1410** [comment]
🙏
