### ISSUE TITLE
Object Inference for EO programs

### ISSUE THREAD

**Issue by yegor256** [objectionary/ideas#13]
Consider this EO program:

```
[] > app
  foo 42
  foo 3.14
[x] > foo
  QQ.io.stdout
    QQ.txt.sprintf
      "Number is %d"
      x
```

It's reasonable to assume that `x` in `foo` may have two possible "types": `int` and `float`.

Let's create a tool that will add such "type" information to an EO program.

Full paper is here: https://www.overleaf.com/read/tgtvcnmmfdjd

**Comment by OlesiaSub** [comment]
@yegor256 working on it. repo [link](https://github.com/OlesiaSub/object-inference-EO), maybe you can add it to objectionary organization?
