### ISSUE TITLE
Algorithmization of object composition

### ISSUE THREAD

**Issue by yegor256** [objectionary/ideas#16]
Consider this EO code:

```
[x] > f
  plus. > @
    x.times x
    42
```

It can be converted to (it's pseudo language):

```
[x] > f
  algo
    """
    input x;
    return x*x + 42;
    """
```

Let's invent a mechanism of doing such transformations and implement a tool that would take `.xmir` file and create a new optimized one. 

Full paper is here: https://www.overleaf.com/read/svbnjqxvhmmd

**Comment by AchekSlime** [comment]
My team will do it as a part of HSE course

**Comment by MikhailLipanin** [comment]
@yegor256, I took this [one](https://github.com/MikhailLipanin/eo-algo-rust)

**Comment by yegor256** [comment]
@MikhailLipanin ok, go ahead
