### ISSUE TITLE
Bug-free release of Qulice

### ISSUE THREAD

**Issue by yegor256** [objectionary/ideas#18]
[Qulice](https://www.qulice.com) is a style checker for Java code, which we actively use in all our projects. At the moment, in its current version 0.22.0, Qulice has many defects, which are reported to [its repository](https://github.com/yegor256/qulice). Let's fix them all and release a new bug-free version of Qulice.

**Comment by MikailBag** [comment]
I would like to participate in this issue as a course project.

**Comment by yegor256** [comment]
@MikailBag OK, go ahead
