### ISSUE TITLE
auto reduction of phi-expressions

### ISSUE THREAD

**Issue by yegor256** [objectionary/ideas#40]
There are expressions in [phi-calculus](https://arxiv.org/abs/2111.13384), for example this one:

```
[ y -> [ z -> 42 ].z ].y
```

It may be reduced to:

```
[ z -> 42 ].z
```

And then to:

```
42
```

There is a dozen of _reduction rules_, which are well defined. We should implement a program, which will take an expression as an input and then show step by step how it is reduced to a _normal form_ (when no rules can be applied any more). The output of the program should be a list of expressions, starting from the incoming expression till the normal form.

I suggest we implement this in [Coq](https://en.wikipedia.org/wiki/Coq).

**Comment by l3r8yJ** [comment]
@yegor256 can i take it? If so, how should I start it, just create a new repo, then move it to `Objectionary`?

**Comment by yegor256** [comment]
should be done by https://github.com/objectionary/normalizer
